// Generates dist/tokens.css — plain CSS custom properties for non-Tailwind
// consumers (e.g. the edge-plane portal's build-free static HTML) — from the
// Tailwind v4 `@theme` source of truth in src/theme.css. Run by `pnpm build`;
// never hand-edit dist/tokens.css. See src/tokens.test.ts for the drift check
// that fails CI if the committed file falls out of sync with theme.css.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const themeCss = readFileSync(join(root, 'src/theme.css'), 'utf8')

/** Return the contents of the first brace-balanced block starting at `from`. */
function extractBlock(css, from) {
  const open = css.indexOf('{', from)
  let depth = 0
  for (let i = open; i < css.length; i++) {
    if (css[i] === '{') depth++
    else if (css[i] === '}') {
      depth--
      if (depth === 0) return css.slice(open + 1, i)
    }
  }
  throw new Error('unbalanced braces')
}

/** Return the full `selector { ... }` text (selector + balanced block). */
function extractRule(css, selectorMatch) {
  const start = selectorMatch.index
  const open = css.indexOf('{', start)
  let depth = 0
  for (let i = open; i < css.length; i++) {
    if (css[i] === '{') depth++
    else if (css[i] === '}') {
      depth--
      if (depth === 0) return css.slice(start, i + 1)
    }
  }
  throw new Error('unbalanced braces')
}

const themeMatch = /@theme\s*/.exec(themeCss)
if (!themeMatch) throw new Error('no @theme block found in src/theme.css')
const themeDecls = extractBlock(themeCss, themeMatch.index)
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .split('\n')
  .filter((line) => line.trim())
  .join('\n')

const plainRootMatch = /:root\s*\{/.exec(themeCss)
if (!plainRootMatch) throw new Error('no plain :root block found in src/theme.css')
const plainRootDecls = extractBlock(themeCss, plainRootMatch.index).trim()

const darkAttrMatch = /:root\[data-theme=['"]dark['"]\]\s*\{/.exec(themeCss)
if (!darkAttrMatch) throw new Error("no :root[data-theme='dark'] block found in src/theme.css")
const darkAttrRule = extractRule(themeCss, darkAttrMatch)

const mediaMatch = /@media\s*\(prefers-color-scheme:\s*dark\)\s*\{/.exec(themeCss)
if (!mediaMatch) throw new Error('no prefers-color-scheme media block found in src/theme.css')
const mediaRule = extractRule(themeCss, mediaMatch)

const output = `/* GENERATED by scripts/build-tokens.mjs from src/theme.css — do not hand-edit.
 * Plain-CSS design tokens for non-Tailwind, non-React consumers (e.g. static
 * HTML pages). Ships the same custom properties as src/theme.css's @theme
 * block, without the Tailwind at-rule wrapper. Re-run \`pnpm build\` after any
 * src/theme.css change so this file stays in sync (checked by
 * src/tokens.test.ts). */

:root {
  ${plainRootDecls}
${themeDecls}
}

${darkAttrRule}

${mediaRule}
`

const outDir = join(root, 'dist')
mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, 'tokens.css'), output)
console.log('wrote dist/tokens.css')
