// @vitest-environment node
//
// Drift check for dist/tokens.css, the generated plain-CSS export for
// non-Tailwind consumers (scripts/build-tokens.mjs, run by `pnpm build`).
// This asserts the *committed* dist/tokens.css still matches the values in
// src/theme.css — if someone edits theme.css without re-running the build
// (or hand-edits tokens.css), this fails CI instead of silently drifting.
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const themeCss = readFileSync(fileURLToPath(new URL('./theme.css', import.meta.url)), 'utf8')
const tokensCss = readFileSync(fileURLToPath(new URL('../dist/tokens.css', import.meta.url)), 'utf8')

/** Extract `--name: value;` declarations from a CSS block as a sorted list. */
function decls(block: string): string[] {
  return [...block.matchAll(/(--[\w-]+):\s*([^;]+);/g)]
    .map((m) => `${m[1]}: ${m[2].trim()}`)
    .sort()
}

test('tokens.css is a generated file with the do-not-hand-edit header', () => {
  expect(tokensCss).toContain('GENERATED by scripts/build-tokens.mjs')
})

test('light tokens match theme.css', () => {
  const themeLight = themeCss.slice(0, themeCss.indexOf(":root[data-theme='dark']"))
  const outLight = tokensCss.slice(0, tokensCss.indexOf(":root[data-theme='dark']"))
  expect(decls(outLight)).toEqual(decls(themeLight))
})

test("dark tokens (:root[data-theme='dark']) match theme.css", () => {
  const themeDark = themeCss.slice(
    themeCss.indexOf(":root[data-theme='dark']"),
    themeCss.indexOf('@media'),
  )
  const outDark = tokensCss.slice(
    tokensCss.indexOf(":root[data-theme='dark']"),
    tokensCss.indexOf('@media'),
  )
  expect(decls(outDark)).toEqual(decls(themeDark))
})

test('media (prefers-color-scheme) tokens match theme.css', () => {
  const themeMedia = themeCss.slice(themeCss.indexOf('@media'))
  const outMedia = tokensCss.slice(tokensCss.indexOf('@media'))
  expect(decls(outMedia)).toEqual(decls(themeMedia))
})

test('color-scheme declarations carry over 1 light / 2 dark, same as theme.css', () => {
  const count = (css: string, value: string) =>
    (css.match(new RegExp(`color-scheme:\\s*${value};`, 'g')) || []).length
  expect(count(tokensCss, 'light')).toBe(count(themeCss, 'light'))
  expect(count(tokensCss, 'dark')).toBe(count(themeCss, 'dark'))
})
